spring:
  application:
    name: bikehub
  config:
    import: "optional:classpath:application-secret.properties"
  datasource:
    url: jdbc:mysql://metro.proxy.rlwy.net:41258/railway
    username: root
    password: BEiBDchfRCeSxPWsDHGxTtSclukaDIrK
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
      file-size-threshold: 2KB

jwt:
  signerKey: "a4aec8aa399e085aa2c40ae8106d7bb6c55c825a6149916bfcc9920e441d05c2"
  valid-duration: 3600
  refreshable-duration: 36000

com:
  bikehub:
    sendgrid:
      api-key:  ${SENDGRID_API_KEY}
      from-email: ${SENDGRID_FROM_EMAIL}
      from-name: ${SENDGRID_FROM_NAME}
    googlevision:
      base-url: https://vision.googleapis.com/v1/images:annotate
      api-key: ${GOOGLE_VISION_API_KEY}

  payos:
    PAYOS_CLIENT_ID: b35ca4d1-0bfd-497e-b61f-ddbcd7eae3e4
    PAYOS_API_KEY: 8996a296-9292-4d54-8edf-6e906426014b
    PAYOS_CHECKSUM_KEY: 95a7817031704749d901816a9c5832e1a7a9e5b8338a906d47f5bbbdf53aff2d

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}


